#!/bin/bash
#SBATCH -p sysgen
#SBATCH --nodes=1
#SBATCH --job-name="SPAdes contigs 3.9.1 assembler comparison"
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32762
#SBATCH --time=10-0:0:00

module load Python/3.5.2-vlsci_intel-2015.08.25

export PATH="/vlsci/SG0006/rwick/SPAdes-3.9.1-Linux/bin:$PATH"

cd /scratch/sysgen/rwick/assembly_test_results

/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/Streptococcus_suis_BM407 --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/random_sequences_no_repeats --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/random_sequences_some_repeats --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/random_sequences_many_repeats --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/Acinetobacter_AB30 --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/Mycobacterium_tuberculosis_H37Rv --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/E_coli_K-12_MG1655 --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/E_coli_O25b_H4-ST131 --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/Klebsiella_NTUH-K2044 --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/Klebsiella_30660_NJST258_1 --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/Klebsiella_MGH_78578 --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/Shigella_sonnei_53G --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/Shigella_dysenteriae_Sd197 --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/Acinetobacter_A1 --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
/scratch/sysgen/rwick/Unicycler-assembly-tests/assembler_comparison-runner.py --fake_read_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/synthetic_reads/Saccharomyces_cerevisiae_S288c --command_file /scratch/sysgen/rwick/Unicycler-assembly-tests/assembly_commands/spades_contigs --out_dir /scratch/sysgen/rwick/assembly_test_results --ref_dir /scratch/sysgen/rwick/Unicycler-assembly-tests/reference_sequences
